[package]
name = "earthmc"
version = "0.0.1"
edition = "2024"

[dependencies]
parking_lot = "0.12"
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
typed-builder = "0.21"
uuid = { version = "1.17", features = ["serde"] }

[dev-dependencies]
insta = "1.43.1"
